Remove the requirement of virtualenv package on remote by using venv
yahoo/ychaos pull request #33
Opened 2021-07-21 06:25 UTC by AlfinST

# Summary

@yahoo/ychaos-dev

Currently, ychaos requires `virtualenv` package to be installed on the target hosts.
With these changes, we should be able to remove that requirement by using `venv` which comes with python3

---

**Fixes**: #7 

## Checklist

### Checklist (Developer)

#### Prerequisites
- [ ] I have read the contribution guidelines

#### Code Analysis
- [ ] Covered by Unittests
- [ ] Security warnings ignored (Why?!)

#### Project related
- [ ] Schema changed and is backward compatible.
- [ ] Introduces a new sub-command for ychaos CLI

### Autogenerated Files
- [ ] Auto generated schema

### Pre-Merge Checklist

- [ ] All the build jobs are passing

---

### Checklist (Reviewer 1)

- [ ] Reviewed Source Code
- [ ] Reviewed Tests (If applicable)
- [ ] Reviewed Documentation (If applicable)

### Checklist (Reviewer 2)

- [ ] Reviewed Source Code
- [ ] Reviewed Tests (If applicable)
- [ ] Reviewed Documentation (If applicable)

2021-07-21 06:29 UTC, AlfinST commented
All testing was done on a newly sprung-up host which just had python3 freshly installed

I noticed that the virtual env we created was using an older version of pip which were causing issues installing one of the dependencies

```
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-2z_fpzk0/cryptography/
You are using pip version 9.0.3, however version 21.1.3 is available.
```
Hence I had to mention to install a later version(20.2.3) of pip

Once that was fixed,
the next issue was while running
```
*** You may need to add PYTHONIOENCODING=utf-8 to your environment ***
```
Hence I had to include to export command while running ychaos on host

2021-07-21 07:37 UTC, shashankrnr32 requested changes

2021-07-21 07:37 UTC, shashankrnr32 commented on src/ychaos/core/executor/MachineTargetExecutor.py
> +                        name="pip==20.2.3",
We shouldn't install a specific version on the target. We can fail the ansible playbook right here if the pip version is not able to install the package

2021-07-21 07:37 UTC, shashankrnr32 commented on src/ychaos/core/executor/MachineTargetExecutor.py
> +                            "export PYTHONIOENCODING=utf-8"
Is this is not a requirement, lets not do this like this, lets explore to get rid of this warning pythonically if possible

2021-07-21 07:45 UTC, shashankrnr32 commented
Can you please add a UT for `MachineTargetExecutor` that fails when and if the playbook tasks are changed?

2021-07-21 16:20 UTC, AlfinST commented on src/ychaos/core/executor/MachineTargetExecutor.py
> +                        name="pip==20.2.3",
Would it be better to have 
```
state=latest
```
so latest pip version is installed?

2021-07-22 06:32 UTC, shashankrnr32 commented on src/ychaos/core/executor/MachineTargetExecutor.py
> +                        name="pip==20.2.3",
I particularly dont like installing pip on the root. We should use the pip already present and check if the version allows us to install ychaos. Otherwise, just exit marking it as failed

@vijaybabu4589 @saravanan-murugesan

2021-07-22 06:46 UTC, AlfinST commented on src/ychaos/core/executor/MachineTargetExecutor.py
> +                        name="pip==20.2.3",
the pip that would be upgraded would be the one in the virtual env
```
$ sudo pip --version
pip 20.2.3 from /root/.local/lib/python3.6/site-packages/pip (python 3.6)
$ source ychaos_env/bin/activate
(ychaos_env) [asthomas@sweepkeep ~]$ pip --version
pip 21.1.3 from /home/asthomas/ychaos_env/lib64/python3.6/site-packages/pip (python 3.6)
```

2021-07-22 06:47 UTC, shashankrnr32 commented on src/ychaos/core/executor/MachineTargetExecutor.py
> +                        name="pip==20.2.3",
That is good. We can upgrade the venv pip version to latest

2021-07-22 10:37 UTC, shashankrnr32 commented on tests/core/executor/test_MachineTargetExecutor.py
> +            "Delete Virtual environment",
Lets assert each step attributes instead of just names. This will mask any change we do to each step.

2021-07-22 12:40 UTC, AlfinST commented on src/ychaos/cli/main.py
> +        sys.stdout = io.open(sys.stdout.fileno(), 'w', encoding='utf8')
Other than looking for a pythonic way to
```bash
export PYTHONIOENCODING=utf-8
```
Using this wrapper over stdout does the trick

There is an option to use 
```python
sys.stdout.reconfigure(encoding='utf-8')
```
but that is only available from python3.7

2021-07-30 04:53 UTC, shashankrnr32 reviewed
Please test this on a VM. Lets discuss on the results on the test and then merge. Changes look good to me.

2021-07-30 05:42 UTC, AlfinST commented
Test on a host after I uninstall virtualenv
```shell
[asthomas@weighedmaid ~]$ sudo pip uninstall virtualenv
Found existing installation: virtualenv 20.4.3
Uninstalling virtualenv-20.4.3:
  Would remove:
    /opt/vz/1.0/bin/virtualenv
    /opt/vz/1.0/lib/python3.9/site-packages/virtualenv-20.4.3.dist-info/*
    /opt/vz/1.0/lib/python3.9/site-packages/virtualenv/*
Proceed (y/n)? y
  Successfully uninstalled virtualenv-20.4.3
  ```
  ```shell
[asthomas@weighedmaid ~]$ pip list
Package    Version
---------- -------
appdirs    1.4.4
distlib    0.3.1
filelock   3.0.12
pip        20.2.3
setuptools 54.2.0
six        1.15.0
wheel      0.36.2
WARNING: You are using pip version 20.2.3; however, version 21.2.1 is available.
You should consider upgrading via the '/opt/vz/1.0/bin/python3.9 -m pip install --upgrade pip' command.
```
ychaos_env has latest pip version
```shell
(ychaos_env) [asthomas@weighedmaid ~]$ pip --version
pip 21.2.1 from /home/asthomas/ychaos_env/lib/python3.9/site-packages/pip (python 3.9)
```
ychaos ran cpu_burn successfullly
```shell
─────────────────── YChaos, The resilience testing framework ───────────────────

                 YChaos CLI configuration                  
┏━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Configuration ┃ Value                                   ┃
┡━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ _command_     │ ychaos ➡ execute                        │
│ config        │ prod                                    │
│ debug         │ False                                   │
│ no_color      │ False                                   │
│ testplan      │ /Users/asthomas/Test/Resilience/TP.yaml │
│ verbose       │ 0                                       │
└───────────────┴─────────────────────────────────────────┘

[11:02:02] Starting app                                              main.py:185
           Getting Test plan                                      __init__.py:88

           Starting attack. executor=machine                       execute.py:48

[11:06:07] Exiting with exitcode=0                                   main.py:279
────────────────────────────────────── ☀ ───────────────────────────────────────

Process finished with exit code 0
```

2021-07-30 05:58 UTC, shashankrnr32 reviewed
Minor nits. We can merge this on Monday. I will test the change once.
Changes look great. Thank you

2021-07-30 05:58 UTC, shashankrnr32 commented on tests/core/executor/test_MachineTargetExecutor.py
> +            self.assertEqual(task, expected_tasks[i])
This should be Dictionary comaparison `assertDictEqual`
```suggestion
            self.assertDictEqual(task, expected_tasks[i])
```

2021-07-30 05:58 UTC, shashankrnr32 commented on tests/core/executor/test_MachineTargetExecutor.py
> +    def test_machine_executor_playbook_tasks_are_in_order(self):
```suggestion
    def test_machine_executor_playbook_tasks_sanity(self):
```

2021-07-30 06:01 UTC, shashankrnr32 commented
Please add an entry in docs/releases.md under Next release 0.2.0

2021-07-30 07:40 UTC, shashankrnr32 commented on docs/releases.md
> +1. Remove the requirement of virtualenv package on remote host by using venv by [Alfin S Thomas](https://github.com/AlfinST)
Please rebase with recent updates. There is already a section for 0.2.0

2021-07-30 10:26 UTC, shashankrnr32 commented
I just tested the change on a VM. Works like a charm. Can you please do these changes to the documentation to remove virtualenv as a requirement.

1. https://github.com/yahoo/ychaos/blob/1cf3a0cb0de542544dff476e64b7bfeef4b04279/docs/get_started.md#L8
2. https://github.com/yahoo/ychaos/blob/1cf3a0cb0de542544dff476e64b7bfeef4b04279/docs/index.md#L71

I will approve once these above doc is updated. Thanks for this PR

2021-07-30 11:22 UTC, shashankrnr32 approved these changes
This is a great improvement. Thanks.

2021-08-02 09:42 UTC, shashankrnr32 submitted a review, later dismissed

2021-08-02 10:47 UTC, shashankrnr32 approved these changes

2021-08-02 10:47 UTC, nafri-irfan96 approved these changes

2021-08-02 10:48 UTC, merged